export const phrases = [
    //    Mask
    "I made a mask for myself",
    "They thought I wanted to rob a shop because of my mask",
    "I left my mask at home when I went out",
    "I ordered a custom mask",
    //  Money
    "I bought bitcoin",
    "I bought shares",
    "I bought foreign currency",
    "I switched banks",
    "I opened a new bank account",
    "Bought concert tickets",
    "Got ticket refund",
    "Plane tickets were refunded",
    //  Work
    "Got a promotion",
    "I worked from home",
    "Got fired",
    "Got a bonus",
    "I worked outside",
    "I always went to my workplace as I usually do",
    "Worked remotely even though my company did not support this before",
    "My salary was decreased",
    "Got financial aid",
    "Petted a dog in a video meeting",
    "I started my own business",
    "I went to an online conference",
    "Worked without clothes",
    "Worked in underwear",
    //  Cooking
    "Made a sourdough starter",
    "Beaked bread",
    "Cooked for myself",
    "Cooked for my family",
    "Named my sourdough starter",
    "Ate the same food for 4 consecutive days",
    "Cooked expired food from the fridge",
    "Homemade pizza",
    "Tasted my pet's food",
    //  Shopping
    "Could not find a parking spot near the mall",
    "Bought more toilet paper than I usually do",
    "Wanted to buy something but others took it all",
    "Pretended I was over 65 years old.",
    "Wanted to buy yeast, but could not find any",
    "Ordered food with a discount related to quarantine",
    "Got sent out of a shop because I was not the proper age",
    "Did not let me in a shop because of my age",
    //  News
    "Listened to the official source of quarantine related information",
    "Started to listen to a new podcast",
    "Installed a tracker app",
    //  Hobbies
    "Watched a whole new series while I was at home",
    "Went to a place to relax I've never been before",
    "Went to the nearest park and it was overcrowded",
    "Went to run",
    "Started a new hobby",
    "Made a quarantine related data visualization",
    "Workout outside",
    "Workout at home",
    "Stopped shaving",
    "Played online board game with friends or family",
    "Painted a picture",
    "Draw something with chalk",
    "Read a book in one day",
    "Meditated",
    "Took online yoga class",
    "Bought a puzzle",
    "Put together a puzzle in one day",
    "Started to learn a new language",
    "Discovered TikTok",
    "Learned a TikTok dance",
    "Took an online course",
    "Reread a favourite book",
    "Rewatched a favourite movie",
    "Rewatched a favourite TV series",
    "Bought an instrument",
    "Started a journal",
    "Planned the week ahead",
    //  Emotions
    "Spent a day without seeing the sunlight",
    "Spent a week without seeing the sunlight",
    "Neighbour drilled the wall for a day",
    "Neighbour drilled the wall for a week",
    "Heard the neighbours having fun",
    "Had an emotional breakdown",
    "Days felt the same for a week",
    "Accidentally locked myself out",
    "Could not leave the house",
    "Talked with a neighbour that I haven't talk with before",
    "Went on virtual therapy",
    "Forgot whether I washed my teeth or not",
    "Forgot what day it is",
    "Went to the fridge to see if something has changed in it",
    "Watched a movie with a crowd scene and felt bad",
    "Judged someone for not social distancing",
    "Sent a postcard",
    "Felt lonely",
    "Got emotional support",
    "Ran out of alcoholic drinks",
    "Counted the days in the wall",
    "Texted my ex",
    "Forgot how to engage in a conversation",
    "Stared at the rain",
    "Stared at the snow",
    "Stared at the clouds",
    "Cried",
    //  Travel
    "Cancelled a trip",
    "Went on a trip",
    "Went on a tour in street view",
    //  Health
    "Touched my face",
    "Washed my hands for 30 seconds",
    "Washed my hands for 60 seconds",
    "Washed my hands for 120 seconds",
    "Stopped myself from touching my face",
    "I was in a hospital",
    "I was infected with the virus",
    "I started a new diet",
    "I realized I was infected after it was over",
    "Disinfected the disinfectant",
    "Skipped showering",
    "Ate only crackers the whole day",
    "Set a reminder to shower",
    "Set a reminder to lunch",
    "I feel healthier since the lockdown started",
    "I feel less healthy since the lockdown started",
]
